# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  app.twig_extension:
    class: Acme\AppBundle\Twig\AppExtension
    public: false
    tags:
      - { name: twig.extension }
  app.validator.avoid_stress_validator:
    class: AppBundle\Constraint\Validator\AvoidStressValidator
    arguments: [ @doctrine.orm.entity_manager ]
    tags:
        - { name: validator.constraint_validator, alias: avoid_stress_validator }